module.exports = {
    'it-weekly': {
        _name: 'IT周刊',
        all: [
            {
                title: 'javascript weekly',
                docs: '',
                source: ['/javascript'],
                target: '/it-weekly/javascript',
            },
            {
                title: 'nodejs weekly',
                docs: '',
                source: ['/nodejs'],
                target: '/it-weekly/nodejs',
            },
            {
                title: 'frontend weekly',
                docs: '',
                source: ['/frontend'],
                target: '/it-weekly/frontend',
            },
            {
                title: 'react status weekly',
                docs: '',
                source: ['/react-status'],
                target: '/it-weekly/react-status',
            },
            {
                title: 'golang weekly',
                docs: '',
                source: ['/golang'],
                target: '/it-weekly/golang',
            },
            {
                title: 'serverless weekly',
                docs: '',
                source: ['/serverless'],
                target: '/it-weekly/serverless',
            },
            {
                title: 'deno news',
                docs: '',
                source: ['/deno'],
                target: '/it-weekly/deno',
            },
            {
                title: 'tailwind weekly',
                docs: '',
                source: ['/tailwind'],
                target: '/it-weekly/tailwind',
            },
            {
                title: 'css weekly',
                docs: '',
                source: ['/css'],
                target: '/it-weekly/css',
            },
            {
                title: 'rust weekly',
                docs: '',
                source: ['/rust'],
                target: '/it-weekly/rust',
            },
            {
                title: 'react weekly',
                docs: '',
                source: ['/react'],
                target: '/it-weekly/react',
            },
            {
                title: 'android weekly',
                docs: '',
                source: ['/android'],
                target: '/it-weekly/android',
            },
            {
                title: 'IOS weekly',
                docs: '',
                source: ['/ios'],
                target: '/it-weekly/ios',
            },
            {
                title: 'js-tools weekly',
                docs: '',
                source: ['/js-tools'],
                target: '/it-weekly/js-tools',
            },
            {
                title: 'web-tools weekly',
                docs: '',
                source: ['/web-tools'],
                target: '/it-weekly/web-tools',
            },
            {
                title: 'typescript weekly',
                docs: '',
                source: ['/typescript'],
                target: '/it-weekly/typescript',
            },
            {
                title: 'postgres weekly',
                docs: '',
                source: ['/postgres'],
                target: '/it-weekly/postgres',
            },
            {
                title: 'jamstack weekly',
                docs: '',
                source: ['/jamstack'],
                target: '/it-weekly/jamstack',
            },
            {
                title: 'vscode weekly',
                docs: '',
                source: ['/vscode'],
                target: '/it-weekly/vscode',
            },
        ],
    },
};
